language: cpp
compiler: gcc
dist: trusty

install:
# Upgrade GCC
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

# Install Ninja
- sudo apt-get install ninja-build

# Install conan
- pip install --user conan # Dependency manager for C/C++

script:
- mkdir build
- cd build
- conan install ..
- cmake .. -GNinja
- ninja
- ninja test
